### ISSUE TITLE
Twist library/Nano 33 BLE issue

### ISSUE THREAD

**Issue by praabye** [sparkfun/SparkFun_Qwiic_Twist_Arduino_Library#3]
Hi! 
I have used your Twist library with Arduino Nano with joy. 
  
Now I have a project in need of an Arduino Nano 33 BLE (mainly for programming space), and tried to move my project to that. It gives a compilation error: 
  
“”” 
C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp: In member function 'boolean TWIST::writeRegister24(uint8_t, uint32_t)': 
C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp:344:28: error: call of overloaded 'write(uint32_t)' is ambiguous 
   _i2cPort->write(val >> 16);  //MSB 
                            ^ 
In file included from C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.h:28:0, 
                 from C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp:25: 
C:\Users\praab\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\libraries\Wire/Wire.h:59:20: note: candidate: virtual size_t arduino::MbedI2C::write(uint8_t) 
     virtual size_t write(uint8_t data); 
                    ^~~~~ 
C:\Users\praab\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\libraries\Wire/Wire.h:60:20: note: candidate: virtual size_t arduino::MbedI2C::write(int) 
     virtual size_t write(int data) { 
                    ^~~~~ 
C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp:345:27: error: call of overloaded 'write(uint32_t)' is ambiguous 
   _i2cPort->write(val >> 8);   //MidMSB 
                           ^ 
In file included from C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.h:28:0, 
                 from C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp:25: 
C:\Users\praab\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\libraries\Wire/Wire.h:59:20: note: candidate: virtual size_t arduino::MbedI2C::write(uint8_t) 
     virtual size_t write(uint8_t data); 
                    ^~~~~ 
C:\Users\praab\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\libraries\Wire/Wire.h:60:20: note: candidate: virtual size_t arduino::MbedI2C::write(int) 
     virtual size_t write(int data) { 
                    ^~~~~ 
C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp:346:29: error: call of overloaded 'write(long unsigned int)' is ambiguous 
   _i2cPort->write(val & 0xFF); //LSB 
                             ^ 
In file included from C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.h:28:0, 
                 from C:\Users\praab\Documents\Arduino\libraries\SparkFun_Qwiic_Twist_Arduino_Library\src\SparkFun_Qwiic_Twist_Arduino_Library.cpp:25: 
C:\Users\praab\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\libraries\Wire/Wire.h:59:20: note: candidate: virtual size_t arduino::MbedI2C::write(uint8_t) 
     virtual size_t write(uint8_t data); 
                    ^~~~~ 
C:\Users\praab\AppData\Local\Arduino15\packages\arduino\hardware\mbed_nano\3.4.1\libraries\Wire/Wire.h:60:20: note: candidate: virtual size_t arduino::MbedI2C::write(int) 
     virtual size_t write(int data) { 
                    ^~~~~ 
  
exit status 1 
  
Compilation error: exit status 1 
“”” 
  
It seems to be in need of a choice of processor in the .h file. I read this as a problem with data size definitions. Am I right?

**Comment by praabye** [comment]
I only had access to std Arduino IDE, and thus haven't tried other environments. But I have tried with Arduino Nano Every, where it worked. So it must be some pragma or other, that's missing for the Arduino Nano Every 33 BLE.

**Comment by nseidle** [comment]
Thanks for reporting. Should be fixed in next release. Please let us know if you still have this problem.
